version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/rest_trello
    ports:
      - 8000:8000
    env_file:
      - ./.env
    container_name: trello_rest

